### ISSUE TITLE
[BUG] Syntax checking for not working

### ISSUE THREAD

**Issue by MVDBMS-Solutions** [mvextensions/mvbasic#41]
The Features documentation says:

> Syntax checking for:
> GOTO/GOSUB's
> LOOPS
> CASE statements
> IF THEN/ELSE statements

Syntax checking does not seem to be enabled by default. Note in the screenshot that there is lots of invalid syntax but no squigglies or other error indicators.
Does the code need to be compiled, and server output returned to the client before syntax issues are flagged?

![image](https://user-images.githubusercontent.com/41167191/65531059-eee1e180-dead-11e9-93c1-547d47236c59.png)

**Versions of applicable software**
  * Windows 8.1
  * Not connected to DBMS
  * MVBASIC Extension v2.0.0
  * VSCode 1.38.1

**Comment by itsxallwater** [comment]
The language server doesn't fire up until you begin to make edits to the document, which is a thing we'd definitely like to change (to fire on load). Can you confirm that if you start typing something in, you'll see the linting, etc. begin to go to work?

**Comment by MVDBMS-Solutions** [comment]
I'm creating new files, adding some code, and saving. I have not installed the MVGateway, and am not using a workspace, just individual files. I have not attached to any server or other process, just installed, set the language, and started poking at the editor.

Is the gateway required to access a MV server in order to provide the features?

**Comment by itsxallwater** [comment]
Re: the gateway, no, I don't have it installed either. I'm working totally disconnected and doing a similar thing in creating new files, adding code, saving and it's at that point where I see the linter pick up and start highlighting errors.

**Comment by MVDBMS-Solutions** [comment]
On reload after installing v2.0.1 it started linting up a storm.
I recommend the Readme for installation via VSCode include a note that (for now anyway) a VSCode reload is required on any installation or update.

**Comment by itsxallwater** [comment]
Glad to hear it, and duly noted. I agree re: the note for the readme and added a line into the install section. I'll be curious to see if future updates require the reload, I noticed it when mine updated and that's counter to how most extension updates are working these days. I know they've done a good job in reducing the amount of times the editor needs to be reloaded, so it'll be interesting to see if that's the norm for us or if it's more due to things switching from the `.vsix` installed version a lot of folks had to the marketplace sourced one, etc.
