### ISSUE TITLE
[BUG] Invalid "Missing NEXT statement"

### ISSUE THREAD

**Issue by mikes-zum** [mvextensions/mvbasic#62]
**Describe the bug**
Missing next statement error generated on this line of code:

FOR I = 32 TO 127; OUT I; NEXT I ;* Printable chars

**To Reproduce**
Insert this line of code in VS Code

See error and "squiggle" underline

**Expected behavior**
Code should be accepted
**Screenshots**

**Versions of applicable software**
Windows 10
VS Code Insiders 1.42.0-insider
MV Basic 2.0.2

**Code samples and/or reproduceable test cases**

FOR I = 32 TO 127; OUT I; NEXT I ;* Printable chars

**Additional context**

**Comment by mikes-zum** [comment]
![Exhibit#1](https://user-images.githubusercontent.com/52958459/71194086-3694c100-2283-11ea-82e5-e0a4a1032fcf.jpg)

**Comment by mikes-zum** [comment]
I should also mention:

	},
				"MVBasic.languageType": {
					"scope": "resource",
					"type": "string",
					"default": "jBASE",
					"enum": [
						"MVON",
						"jBASE",
						"UniVerse",
						"OpenQM"
					],

**Comment by kpowick** [comment]
It should probably just be a warning that, though valid,  this code is poorly written.  ;)

**Comment by mikes-zum** [comment]
I am in the process of validating all of my jBASE documentation changes and in most cases also using the code examples from the same pages as the documentation.

The resulting source code may then be useful for (MVBasic) testing purposes .

**Comment by ianmcgowan** [comment]
This is caused by validateTextDocument in server/src/server.ts.   This function is called whenever the document changes, and goes through line-by-line validating (as the name suggests :-)

For FOR/NEXT loops, it builds a cross-reference as it goes through the program, also incrementing a counter for each FOR and another for each NEXT.  If the counts don't match at the end, it goes through the cross-reference crossing out the ones that do match and any missing ones are added to the list of diagnostic warnings.

E.g. "1~+F|3~-F" if the program has FOR F=1 TO 10 in line 1, and then NEXT F in line 3.

![image](https://user-images.githubusercontent.com/408975/71237577-c3a53d80-22b6-11ea-82ce-aa50cd008db4.png)

One fix is to have some slightly more complex parsing for the FOR F=1 TO 10; CRT F; NEXT F case, where the trailing NEXT F is picked up and handled as though it was on its own line.

Another fix, arguably the correct one - the parser should break statements with embedded semi-colons onto their own lines and then process them independently (like the BASIC compiler would).  This is technically correct, but carries a lot more risk of getting things wrong.

**Comment by ianmcgowan** [comment]
I created a pull request https://github.com/mvextensions/mvbasic/pull/63 for a change to fix this - it works by splitting lines with embedded semi-colons into separate new lines.  That should help any linting errors with multiple statements on one line, but does have the unfortunate side-effect of throwing off the line number reported for the error.  Also improved the FOR/NEXT checking (I think), but would like Grant's opinion on the change.

**Comment by kpowick** [comment]
@ianmcgowan Does this only apply to FOR/NEXT checking? i.e. The file is parsed in this new way only to calculate FOR/NEXT?

If so, does semicolon checking consider the implied "END" statement in single-line, multi-statement IF/THEN constructs?  Example:
```
IF TRUE THEN CRT "TRUE";STOP
```
The compiler interprets the above as:
```
IF TRUE THEN
   CRT "TRUE"
   STOP
END

```
I guess I would have a better idea of how this worked if I looked at the project code, but I haven't had time.  It's just that this issue caught my attention.

**Comment by ianmcgowan** [comment]
Shoot, @kpowick , that's a really good point.  No, this change is for all lines with substatements. The linter (w/this pull request), would treat that example as:
```
IF TRUE THEN CRT "TRUE"
STOP
```
Which is ok from a linting perspective, but if there're ELSE's and END's in there may fall apart.

I probably need to add two test R83 basic programs: one with legal syntax but including as many tricky cases as possible, and another with tons of illegal syntax to make sure the linter is catching it all.

It's possible to figure it out (the basic compiler does it after all), just not sure how much javascript code that would end up taking.  I'm thinking a lot :-(

**Comment by itsxallwater** [comment]
I like the idea of adding additional test programs. You'll see we've started to do that under the tests directory, specifically for jBASE. By all means push a PR to add more! Will make all of this dev much easier, and at some point I'm hopefully to setup some automated testing that'll leverage them too.

**Comment by kpowick** [comment]
>...That should help any linting errors with multiple statements on one line, but does have the unfortunate side-effect of throwing off the line number reported for the error.

Does the line number being thrown off affect only the specific For/Next error line, or does it throw off all subsequent error line reporting?  Just wondering how "ugly" it could get.

**Comment by ianmcgowan** [comment]
It affects all subsequent lines, but I'm working on something to store the
original line number, and report that in the error.

https://github.com/ianmcgowan/mvbasic/blob/for_next_pull_2/tests/pick/R83GOOD.b

Is an initial test file (of things that are legal syntax), and it does seem
that linting is not thrown off by splitting lines, at least with my basic
BASIC syntax.

**Comment by itsxallwater** [comment]
This may be resolved now between latest + https://github.com/mvextensions/mvbasic/pull/94. Revisited some of the above samples and I'm no longer seeing any issues. @kpowick want to put eyes on this too?
